# Generated by Django 4.1.7 on 2023-03-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.TextField(default='non definie')),
                ('email', models.EmailField(default='non definie', max_length=254)),
                ('telephone', models.CharField(max_length=8)),
            ],
        ),
    ]
