# Generated by Django 4.1.7 on 2023-05-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_alter_commande_datecde'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='fournisseurs',
            field=models.ManyToManyField(to='magasin.fournisseur'),
        ),
    ]
